name: CI

on: [push]

jobs:
  build:

    # https://help.github.com/en/articles/virtual-environments-for-github-actions#supported-virtual-environments
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - run: sudo apt update
    - run: sudo apt install -y libopenblas-dev libopencv-dev

    - name: build
      run: |
        ./configure
        make

    - name: run example
      run: |
        ./bin/example-main
